In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'class':['A','B','A','C','B','C'],
    'marks':[60,55,57,78,78,89]
}
df=pd.DataFrame(data)
result=df.groupby('class')['marks'].mean()
print(result)

class
A    58.5
B    66.5
C    83.5
Name: marks, dtype: float64

In [5]:
df.groupby('class')['marks'].mean()    # Har class ka average marks
df.groupby('class')['marks'].sum()     # Har class ka total marks
df.groupby('class')['marks'].count()   # Har class mein kitne students hain
df.groupby('class')['marks'].max()     # Har class ka highest marks
df.groupby('class')['marks'].min()     # Har class ka lowest marks

class
A    57
B    55
C    78
Name: marks, dtype: int64

In [7]:
import seaborn as sns
titanic=sns.load_dataset('titanic')
print(titanic)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [11]:
titanic.groupby('pclass')['fare'].agg(['mean','max','min'])

             mean       max  min
pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.675550   69.5500  0.0

In [12]:
titanic.groupby('pclass')['fare'].agg(['mean', 'max', 'min'])

             mean       max  min
pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.675550   69.5500  0.0